buysell/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='homeview'),
    path('login/', views.loginview, name='loginview'),
    path('signup/', views.signup_view, name='signupview'),
    path('add-post/', views.addpostview, name='addpostview'),
    path('logout/', views.logoutview, name='logoutview'),
    path('all-ads/<location>/', views.sorted_locview, name='sorted_locview'),
    path('category/<category>/', views.categoryview, name='categoryview'),
    path('product/<url>/', views.productview, name='productview'),
    path('search/query=<query>', views.searchview, name='searchview'),
    path('upload/<id>', views.uploadview, name='uploadview'),
    path('uploads/', views.uploadview2, name='uploadview2'),
    path('edit/<pk>/', views.ProductUpdateView.as_view(), name='product_update'),
    path('delete/<pk>/', views.ProductDelete.as_view(), name='product_delete'),
    path('save/<id>/', views.productSaveview, name='product_saveview'),
    path('unlike/<id>/', views.unlineview, name='product_unlikeview'),
    path('saved/<user>/', views.savedproductview,
         name='product_savedproductview'),
    path('my-products/<user>/', views.myproductview, name='myproductview'),
]

nBuySell/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('buysell.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

buysell/models.py
from django.db import models
from django.contrib.auth.models import User

from django.db.models.signals import post_save
from django.dispatch import receiver


class Image(models.Model):
    image = models.ImageField(upload_to='products')


class Category(models.Model):
    category = models.CharField(max_length=20)

    def __str__(self):
        return str(self.category)


class Location(models.Model):
    name = models.CharField(max_length=20)

    def __str__(self):
        return str(self.name)


class Product(models.Model):
    name = models.TextField(max_length=100)
    price = models.IntegerField()
    condition_opt = (
        ('used', 'Used'),
        ('new', 'New'),
    )
    post_cat = (
        ('sell', 'Sell'),
        ('buy', 'Buy')
    )
    category = models.ForeignKey(
        Category, on_delete=models.SET_NULL, null=True)
    condition = models.CharField(max_length=10, choices=condition_opt)
    post_category = models.CharField(max_length=10, choices=post_cat)
    details = models.TextField(max_length=300)
    is_negotiable = models.BooleanField(default=True)
    location = models.ForeignKey(
        Location, on_delete=models.SET_NULL, null=True)
    uploaded_time = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    phone = models.TextField(max_length=13)
    url = models.TextField(max_length=40)
    image = models.ManyToManyField(Image, blank=True)

    def __str__(self):
        return str(self.name)

    class Meta:
        ordering = ['uploaded_time']


class LovedProduct(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    Product = models.ManyToManyField(Product, blank=True)


@receiver(post_save, sender=User)
def my_handler(sender, **kwargs):
    if kwargs.get('created'):
        LovedProduct.objects.create(user=kwargs.get('instance'))

buysell/forms.py
from django.forms import ModelForm, TextInput, Select, NumberInput, FileInput, Textarea, ModelChoiceField
from .models import Product, Category


class ProductForm(ModelForm):
    class Meta:
        model = Product
        fields = [
            'name',
            'price',
            'is_negotiable',
            'condition',
            'post_category',
            'location',
            'details',
            'author',
            'phone',
            'category'

        ]
        widgets = {'name': TextInput(attrs={'class': 'form-control', 'placeholder': 'Product Name'}),
                   'price': NumberInput(attrs={'class': 'form-control', 'placeholder': '$'}),
                   'condition': Select(attrs={'class': 'form-control', 'placeholder': '$'}),
                   'category': Select(attrs={'class': 'form-control'}),
                   'location': Select(attrs={'class': 'form-control'}),
                   'post_category': Select(attrs={'class': 'form-control', 'placeholder': '$'}),
                   'phone': TextInput(attrs={'class': 'form-control', 'placeholder': '017000000'}),
                   'author': TextInput(attrs={'class': 'form-control', 'type': 'hidden', 'value': '{{ request.user.id}}'}),
                   'details': Textarea(attrs={'class': 'form-control', 'rows': "3",
                                               'placeholder': 'ex: 256GB, Color: Royal Blue, Battery: 88%;'}),
                   }

buysell/views.py
from django.core.exceptions import PermissionDenied
from django.http import HttpResponse
from django.shortcuts import render, redirect, HttpResponseRedirect
from .models import Product, Category, Image, Location, LovedProduct
from datetime import datetime, timedelta
from django.contrib.auth import authenticate, login, logout
from .forms import ProductForm
from django.views.generic.edit import UpdateView, DeleteView
from django.contrib.auth.mixins import UserPassesTestMixin


class ProductDelete(UserPassesTestMixin, DeleteView):
    model = Product

    def test_func(self):
        return self.request.user.username == str(self.get_object().author)
    success_url = '../../'
    template_name = 'product_confirm_delete.html'


class ProductUpdateView(UserPassesTestMixin, UpdateView):
    model = Product

    def test_func(self):
        return self.request.user.username == str(self.get_object().author)
    form_class = ProductForm
    template_name = 'product_update_form.html'
    success_url = '../../'


def search(query):
    return redirect('searchview', query=query)


def categories():
    categories = Category.objects.all()
    proCountbyCategory = []
    for category in categories:
        name = category.category
        number = Product.objects.all().filter(category=category.id).count()
        proCountbyCategory.append({'name': name, 'number': number})

    return proCountbyCategory


def locations():
    locations = Location.objects.all()
    locCountbyloc = []
    for loc in locations:
        name = loc.name
        number = Product.objects.all().filter(location=loc.id).count()
        locCountbyloc.append({'name': name, 'number': number})

    return locCountbyloc


def home(request):
    images = Image.objects.all()
    if request.method == 'POST':
        response = search(request.POST['query'])
        return response
    else:
        cateroylist = categories()
        locationlist = locations()
        products = Product.objects.all()
        return render(request, 'home.html', {
            'products': products,
            'categories': cateroylist,
            'locations':  locationlist,
            'images': images
        })


def signup_view(request):
    redirect_to = request.GET.get('next', '')
    if request.method == 'POST' and not request.user.is_authenticated:
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(redirect_to)
        else:
            return render(request, 'signup/index.html', {'redirect_to': redirect_to})
    elif request.user.is_authenticated:
        return redirect('homeview')
    else:
        return render(request, 'signup/index.html', {'redirect_to': redirect_to})


def loginview(request):
    redirect_to = request.GET.get('next', '')
    if request.method == 'POST' and not request.user.is_authenticated:
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(redirect_to)
        else:
            return render(request, 'login/index.html', {'redirect_to': redirect_to})
    elif request.user.is_authenticated:
        return redirect('homeview')
    else:
        return render(request, 'login/index.html', {'redirect_to': redirect_to})


def url_generetor(title):
    product_url = title.replace(' ', '-').lower()
    urlfound = Product.objects.all().filter(url=product_url).count()
    temp = product_url
    while urlfound != 0:
        product_url = temp + '-' + str(urlfound)
        newcount = Product.objects.all().filter(url=product_url).count()
        if newcount:
            urlfound += 1
        else:
            urlfound = 0
    return product_url


def addpostview(request):
    if request.method == 'POST':
        name = request.POST['name']
        price = request.POST['price']
        condition = request.POST['condition']
        category = Category.objects.get(id=request.POST['category'])
        location = Location.objects.get(id=request.POST['location'])
        post_category = request.POST['post_category']
        details = request.POST['details']
        phone = request.POST['phone']
        url = url_generetor(name)
        product = Product.objects.create(
            name=name,
            author=request.user,
            price=price,
            condition=condition,
            category=category,
            post_category=post_category,
            location=location,
            phone=phone,
            url=url,
            details=details
        )

        product.save()
        return redirect('uploadview', product.id)
    else:
        form = ProductForm
        return render(request, 'add-post.html', {'form': form})


def logoutview(request):
    logout(request)
    return redirect('homeview')


def sorted_locview(request, location):
    if request.method == 'POST':
        response = search(request.POST['query'])
        return response
    else:
        cateroylist = categories()
        locationlist = locations()
        loc_object = Location.objects.get(name=location)
        products = Product.objects.all().filter(location=loc_object.id)
        return render(request, 'home.html', {
            'products': products,
            'categories': cateroylist,
            'locations': locationlist,
        })


def categoryview(request, category):
    if request.method == 'POST':
        response = search(request.POST['query'])
        return response
    else:
        category_object = Category.objects.get(category=category)
        products = Product.objects.all().filter(category=category_object.id)
        cateroylist = categories()
        locationlist = locations()
        return render(request, 'home.html', {
            'products': products,
            'categories': cateroylist,
            'locations': locationlist,
        })


def productview(request, url):
    isLoved = False
    product = Product.objects.get(url=url)
    if request.user.is_authenticated:
        user_loved = LovedProduct.objects.filter(user=request.user).first()
        print("user found")

        isLoved = False
        if user_loved:
            found_love = LovedProduct.objects.filter(
                user=request.user, Product=product.id).first()

        if found_love:
            isLoved = True
            print("found love")

    context = {
        'product': product,
        'isLoved': isLoved,
    }
    return render(request, 'product.html', context)


def searchview(request, query):
    if request.method == 'POST':
        response = search(request.POST['query'])
        return response

    search_list = query.split()
    products = Product.objects.all().filter(name__contains=query)

    for text in search_list:
        products = products | Product.objects.all().filter(name__contains=text)

    cateroylist = categories()
    return render(request, 'home.html', {
        'products': products,
        'categories': cateroylist})


def uploadview(request, id):
    product_exit = Product.objects.filter(id=id).count()
    if product_exit and Product.objects.get(id=id).author == request.user:
        return render(request, 'upload-image.html', {'id': id, 'product': Product.objects.get(id=id)})
    else:
        return redirect('homeview')


def uploadview2(request):
    if request.method == 'POST':
        file = request.FILES.get('file')
        product = Product.objects.get(id=request.POST['id'])
        if product.author == request.user:
            image = Image.objects.create(image=file)
            product.image.add(image)
    return HttpResponse('upload')


def productSaveview(request, id):
    redirect_to = request.GET.get('next', '')
    object = LovedProduct.objects.get(user=request.user.id)
    product = Product.objects.get(id=id)
    object.Product.add(product)
    return redirect(redirect_to)


def unlineview(request, id):
    redirect_to = request.GET.get('next', '')
    object = LovedProduct.objects.get(user=request.user.id)
    product = Product.objects.get(id=id)
    object.Product.remove(product)
    return redirect(redirect_to)


def savedproductview(request, user):
    if request.user.username == user:
        object = LovedProduct.objects.get(user=request.user)
        products = object.Product.all()
        context = {
            'products': products,
            'title': 'My saved products list'
        }
        return render(request, 'filter-products.html', context)
    else:
        raise PermissionDenied


def myproductview(request, user):
    if request.user.username == user:
        products = Product.objects.all().filter(author=request.user)
        context = {
            'products': products,
            'title': 'My products list'
        }
        return render(request, 'filter-products.html', context)
    else:
        raise PermissionDenied

buysell/templates/add-post.html
{% extends "base.html" %}
{% block main %}
    {% load static %}
{% if not user.is_authenticated %}
    <meta http-equiv="REFRESH" content="0;url={% url 'loginview' %}?next={{request.path|urlencode}}">
  {% endif %}
    <section class="body post-main container">
      <div class="container">
        <form action="" method="post" class="form" enctype="multipart/form-data">
          {% csrf_token %}
          <div class="row">
            <div class="col-md-5">
            <label for="id_name">Name</label>
              {{ form.name }}
              </div>
            <div class="col-md-2">
            <label for="id_condition">Condition</label>
              {{ form.condition }}
              </div>
            <div class="col-md-3">
              <label for="id_category">Category</label>
              {{ form.category }}
            </div>

          </div>
          <div class="row">
            <div class="col-md-2">

            <label for="id_price">Price</label>
              {{ form.price }}
            </div>
            <div class="col-md-2">

              <label for="id_post_category">Want to</label>
                {{ form.post_category }}
            </div>
            <div class="col-md-2">
              <label for="id_location">Location</label>
                {{ form.location }}
              </div>

             <div class="col-md-3">
              <label for="id_details">Phone</label>
                {{ form.phone }}
            </div>

          </div>

          <div class="row">

            <div class="col-md-4">
              <label for="id_details">Details</label>
                {{ form.details }}
            </div>

            <div class="col-md-3  sub-btn">
              <input class="btn btn-success" type="submit" value="Submit">
            </div>
          </div>



        </form>
      </div>
    </section>
{% endblock %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js" integrity="sha512-894YE6QWD5I59HgZOGReFYm4dnWc1Qt5NtvYSaNcOP+u1T9qYdvdihz0PPSiiqn/+/3e7Jo4EaG7TubfWGUrMQ==" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.min.js" integrity="sha384-+YQ4JLhjyBLPDQt//I+STsc9iw4uQqACwlvpslubQzn4u2UU2UFM80nGisd026JF" crossorigin="anonymous"></script>

buysell/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    {% load static %}
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title>Document</title>
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
      integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css"
    />
    {% block css %} {% endblock %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light">
      <div class="container">
        <button
          class="navbar-toggler"
          type="button"
          data-toggle="collapse"
          data-target="#navbarTogglerDemo01"
          aria-controls="navbarTogglerDemo01"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
          <a class="navbar-brand" href="{% url 'homeview' %}">nBuySell</a>
          <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
            <li class="nav-item active">
              <a class="nav-link btn btn-warning" href="{% url 'homeview' %}"
                >All Adds <span class="sr-only">(current)</span></a
              >
            </li>
          </ul>
          <a class="btn btn-white" href="#"><i class="bi bi-chat"></i> Chat </a>
          {% if not user.is_authenticated %}
          <a
            class="btn btn-white"
            href="{% url 'loginview' %}?next={{request.path | urlencode }}"
            ><i class="bi bi-person"></i> Login</a
          >
          {% else %}
          <li style="list-style: none" class="nav-item dropdown">
            <a
              class="nav-link dropdown-toggle"
              href="#"
              id="navbarDropdown"
              role="button"
              data-toggle="dropdown"
              aria-haspopup="true"
              aria-expanded="false"
            >
              <i class="bi bi-person"></i> {{ request.user.username }}
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a
                class="dropdown-item"
                href="{% url 'product_savedproductview' user=request.user.username %}"
                >Saved Product</a
              >
              <a
                class="dropdown-item"
                href="{% url 'myproductview' user=request.user.username %}"
                >My Product</a
              >
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="{% url 'logoutview' %}">Logout</a>
            </div>
          </li>
          {% endif %}

          <a class="btn btn-success" href="{% url 'addpostview' %}">Add post</a>
        </div>
      </div>
    </nav>

    {% block main %} {% endblock %}

    <footer>
      <hr />
      <div class="container">
        <div class="row">
          <div class="col-md-6">
            &#169; Made with &#10084;&#65039; by
            <a href="http://nbappy.me/">Bappy</a>
          </div>
          <div class="col-md-6 brand">nBuySell</div>
        </div>
      </div>
    </footer>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"
      integrity="sha512-894YE6QWD5I59HgZOGReFYm4dnWc1Qt5NtvYSaNcOP+u1T9qYdvdihz0PPSiiqn/+/3e7Jo4EaG7TubfWGUrMQ=="
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.min.js"
      integrity="sha384-+YQ4JLhjyBLPDQt//I+STsc9iw4uQqACwlvpslubQzn4u2UU2UFM80nGisd026JF"
      crossorigin="anonymous"
    ></script>

    {% block js %} {% endblock %}
  </body>
</html>

buysell/templates/filter-products.html
{% extends "base.html" %}
{% block main %}
<div class="container main-content">
    <div class="row justify-content-center m-5">
        <div class="col-md-6">
            <div class="h4 mt-5 mb-5">{{ title | title}}</div>
            {% if products %}
              {% for product in products %}
            <div class="product">
              <a href="{% url 'productview' url=product.url %}" class="product">
                <div class="listing">
                  <div class="row">
                    <div class="col-md-4">
                      {% for image in product.image.all|slice:":1"  %}
                      <img src="{{ image.image.url }}" alt="">
                      {% endfor %}
                    </div>
                    <div class="col-md-8">
                      <div class="details">
                        <div class="title">
                          <p class="ti">
                            {{ product.name| title | truncatewords:7 }}
                          </p>
                        </div>
                        <div class="description">
                          <div class="det">
                            <p>{{ product.details| truncatewords:4 }}</p>
                          </div>
                          <div class="loc-cat">
                            <p><i class="bi bi-geo-alt"></i> {{ product.location|title }}, {{ product.category|title }}</p>
                          </div>
                          <div class="time-price">
                            <div class="row">
                              <div class="col-md-8">
                                <p class="price">TK {{ product.price }}</p>
                              </div>

                                <div class="col-md-4">
                                  {% if product.uploaded_time|timesince|wordcount > 2 %}

                                    {{ product.uploaded_time|timesince|truncatewords:2|slice:":-3" }}

                                  {% else %}

                                   {{ product.uploaded_time|timesince }}

                                  {% endif %}
                                  </div>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </a>
                </div>
              {% endfor %}
              {% else %}
              <p>There is no Products availble</p>
              {% endif %}
        </div>
    </div>
</div>

{% endblock %}

buysell/templates/home.html
{% extends "base.html" %}
{% block main %}

    <section class="body container">
      <div class="top">
        <div class="container">
          <div class="row">
            <div class="col-md-6">
              <p class="loc"><a href="{% url 'sorted_locview' location='dhaka' %}"><i class="bi bi-geo-alt-fill"></i> Dhaka</a></p>
            </div>
            <div class="col-md-6">
              <form method="post" class="search form-inline">
                {% csrf_token %}
                <input name="query"
                  type="text"
                  class="form-control form-group"
                  placeholder="Search Products"
                />
                <input
                  class="form-group form-control text-white bg-success"
                  type="submit"
                  value="Search"
                />
              </form>
            </div>
          </div>
        </div>
      </div>
      <hr />
      <div class="main-content">
        <div class="container">
          <div class="row">
            <div class="col-md-4">
                <div class="h5"><p>All Categories</p></div>
              <div class="cat">
                {% for category in categories %}
                <p><a href="{% url 'categoryview' category=category.name %}">{{ category.name | title }} ({{ category.number }})</a></p>
                {% endfor %}
              </div>
              <hr>
              <div class="h5"><p>Area</p></div>
              <div class="cat">
                {% for location in locations %}
                <p><a href="{% url 'sorted_locview' location=location.name %}">{{ location.name | title }} ({{ location.number }})</a></p>
                {% endfor %}
              </div>

            </div>
            <div class="col-md-6">
              <div class="page-bread">
                <a href="#" class="page">Home/all-adds/Dhaka</a>
              </div>
              <div class="message">
                <p class="msg">Buy and Sell Anything in Dhaka</p>
                <p class="list-count">Showing 1-25 of 169,938 ads</p>
              </div>
              <hr />
              {% if products %}
              {% for product in products %}
              <a href="{% url 'productview' url=product.url %}" class="product">
                <div class="listing">
                  <div class="row">
                    <div class="col-md-4">
                      {% for image in product.image.all|slice:":1"  %}
                      <img src="{{ image.image.url }}" alt="">
                      {% endfor %}

                    </div>
                    <div class="col-md-8">
                      <div class="details">
                        <div class="title">
                          <p class="ti">
                            {{ product.name| title | truncatewords:7 }}
                          </p>
                        </div>
                        <div class="description">
                          <div class="det">
                            <p>{{ product.details| truncatewords:4 }}</p>
                          </div>
                          <div class="loc-cat">
                            <p><i class="bi bi-geo-alt"></i> {{ product.location|title }}, {{ product.category|title }}</p>
                          </div>
                          <div class="time-price">
                            <div class="row">
                              <div class="col-md-8">
                                <p class="price">TK {{ product.price }}</p>
                              </div>

                                <div class="col-md-4">
                                  {% if product.uploaded_time|timesince|wordcount > 2 %}

                                    {{ product.uploaded_time|timesince|truncatewords:2|slice:":-3" }}

                                  {% else %}

                                   {{ product.uploaded_time|timesince }}

                                  {% endif %}
                                  </div>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </a>
              {% endfor %}
              {% else %}
              <p>There is no Products availble</p>
              {% endif %}
            </div>
          </div>
        </div>
      </div>
    </section>
{% endblock %}

buysell/templates/product_confirm_delete.html
{% extends "base.html" %}
{% block main %}
<div class="container">
    <div class=" row justify-content-center m-5">
        <div class="col-md-6">
        <form method="post">
          {% csrf_token %}
            <p>Are you sure you want to delete "{{ object }}"?</p>
            <input type="submit" value="Confirm">
        </form>
        </div>
    </div>
</div>

{% endblock %}

buysell/templates/product_update_form.html
{% extends "base.html" %}
{% block main %}
<div class="container">
    <div class=" row justify-content-center m-5">
        <div class="col-md-6">
        <form method="post">{% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Update">
        </form>
            </div>
    </div>
</div>

{% endblock %}

buysell/templates/upload-image.html
{% extends "base.html" %}
{% block css%}
{% load static %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/dropzone/5.9.2/basic.min.css" integrity="sha512-MeagJSJBgWB9n+Sggsr/vKMRFJWs+OUphiDV7TJiYu+TNQD9RtVJaPDYP8hA/PAjwRnkdvU+NsTncYTKlltgiw==" crossorigin="anonymous" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/dropzone/5.9.2/dropzone.min.css" integrity="sha512-jU/7UFiaW5UBGODEopEqnbIAHOI8fO6T99m7Tsmqs2gkdujByJfkCbbfPSN4Wlqlb9TGnsuC0YgUgWkRBK7B9A==" crossorigin="anonymous" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/dropzone/5.9.2/dropzone-amd-module.min.js" integrity="sha512-llCHNP2CQS+o3EUK2QFehPlOngm8Oa7vkvdUpEFN71dVOf3yAj9yMoPdS5aYRTy8AEdVtqUBIsVThzUSggT0LQ==" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/dropzone/5.9.2/min/dropzone.min.js" integrity="sha512-VQQXLthlZQO00P+uEu4mJ4G4OAgqTtKG1hri56kQY1DtdLeIqhKUp9W/lllDDu3uN3SnUNawpW7lBda8+dSi7w==" crossorigin="anonymous"></script>

{% endblock %}
{% block main %}
    <section class="body container">
        <div class="details">
            <div class="row">
                <div class="col-md-6 p-3">
                    <div class="h6">
                        Upload photos For your:
                        <strong>{{ product.name }}</strong>

                    </div>
                </div>
            </div>
        </div>
        <form action="../uploads/" method="post" class="dropzone">
            {% csrf_token %}

             <input name="id" type="hidden" value="{{ id }}" />
            <div class="fallback">
                <input name="file" type="file" multiple />
            </div>
        </form>

    </section>
<script>
    var myDropzone = new Dropzone(".dropzone", {
        maxFiles: 2,
        maxFilesize: 3,
        acceptedFiles: ".jpg, .png",

      });

</script>
{% endblock %}

{% block js %}
{% endblock %}